#!/usr/bin/env ruby
#
# from https://github.com/daumiller/ssdp/blob/master/example/roku_play_pause.rb

require 'ssdp'
require 'net/http'
finder = SSDP::Consumer.new :timeout => 3, :first_only => true
result = finder.search :service => 'roku:ecp'
if result.nil?
  puts "Couldn't find a Roku device (they are known to frequently stop respoding to SSDP requests...)."
else
  puts result.inspect
  location = result[:params]['LOCATION']
  puts "Roku device found at #{location}, sending play/pause."
  components = /^[Hh][Tt][Tt][Pp]:\/\/([0-9\.]+):([0-9]+)\/$/.match location

  puts components.inspect
  http = Net::HTTP.new components[1], components[2]
  http.post '/keypress/Play', nil
end
